import type { FanoutTracePath } from "@tscircuit/core";
// Board copper escapes from unchanged supplier pad centres; not component definitions.
export const radioEscapePaths: FanoutTracePath[] = [
	{
		connection: "U1.pin5",
		route: [
			{
				route_type: "wire",
				x: 6.50494,
				y: -17.124458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 8.6,
				y: -17.124458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: 8.6,
				y: -17.124458,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin14",
		route: [
			{
				route_type: "wire",
				x: 2.54,
				y: -10.274586,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 2.54,
				y: -11.5,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: 2.54,
				y: -11.5,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin16",
		route: [
			{
				route_type: "wire",
				x: 1.27,
				y: -10.274586,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 1.27,
				y: -11.5,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: 1.27,
				y: -11.5,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin19",
		route: [
			{
				route_type: "wire",
				x: -0.635,
				y: -8.174514,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -0.635,
				y: -5.8,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -0.635,
				y: -5.8,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin20",
		route: [
			{
				route_type: "wire",
				x: -1.27,
				y: -10.274586,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -1.27,
				y: -11.5,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -1.27,
				y: -11.5,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin21",
		route: [
			{
				route_type: "wire",
				x: -1.905,
				y: -8.174514,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -1.905,
				y: -5.8,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -1.905,
				y: -5.8,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin23",
		route: [
			{
				route_type: "wire",
				x: -3.175,
				y: -8.174514,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -3.175,
				y: -5.8,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -3.175,
				y: -5.8,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin24",
		route: [
			{
				route_type: "wire",
				x: -3.81,
				y: -10.274586,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -3.81,
				y: -11.5,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -3.81,
				y: -11.5,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin26",
		route: [
			{
				route_type: "wire",
				x: -6.50494,
				y: -10.774458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -8.6,
				y: -10.774458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -8.6,
				y: -10.774458,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin37",
		route: [
			{
				route_type: "wire",
				x: -6.50494,
				y: -18.394458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -8.6,
				y: -18.394458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -8.6,
				y: -18.394458,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U1.pin39",
		route: [
			{
				route_type: "wire",
				x: -6.50494,
				y: -19.664458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -8.6,
				y: -19.664458,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -8.6,
				y: -19.664458,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.6,
				via_hole_diameter: 0.3,
			},
		],
	},
];
