/// <reference types="@tscircuit/cli/types/static-assets" />
// Generated by tools/build-model-manifest.py; supported static asset imports.
import model0 from "./models/FrozenR6-Box0.glb";
import model1 from "./models/FrozenR6-C1.glb";
import model2 from "./models/FrozenR6-C2.glb";
import model3 from "./models/FrozenR6-C3.glb";
import model4 from "./models/FrozenR6-C4.glb";
import model5 from "./models/FrozenR6-C5.glb";
import model6 from "./models/FrozenR6-C6.glb";
import model7 from "./models/FrozenR6-C7.glb";
import model8 from "./models/FrozenR6-C8.glb";
import model9 from "./models/FrozenR6-C9.glb";
import model10 from "./models/FrozenR6-J1.glb";
import model11 from "./models/FrozenR6-J2.glb";
import model12 from "./models/FrozenR6-J3.glb";
import model13 from "./models/FrozenR6-LED1.glb";
import model14 from "./models/FrozenR6-LED2.glb";
import model15 from "./models/FrozenR6-Q1.glb";
import model16 from "./models/FrozenR6-Q2.glb";
import model17 from "./models/FrozenR6-R1.glb";
import model18 from "./models/FrozenR6-R10.glb";
import model19 from "./models/FrozenR6-R11.glb";
import model20 from "./models/FrozenR6-R12.glb";
import model21 from "./models/FrozenR6-R13.glb";
import model22 from "./models/FrozenR6-R2.glb";
import model23 from "./models/FrozenR6-R3.glb";
import model24 from "./models/FrozenR6-R4.glb";
import model25 from "./models/FrozenR6-R5.glb";
import model26 from "./models/FrozenR6-R6.glb";
import model27 from "./models/FrozenR6-R7.glb";
import model28 from "./models/FrozenR6-R8.glb";
import model29 from "./models/FrozenR6-R9.glb";
import model30 from "./models/FrozenR6-SW1.glb";
import model31 from "./models/FrozenR6-SW2.glb";
import model32 from "./models/FrozenR6-SW3.glb";
import model33 from "./models/FrozenR6-U1.glb";
import model34 from "./models/FrozenR6-U2.glb";
import model35 from "./models/FrozenR6-U3.glb";
import model36 from "./models/FrozenR6-U4.glb";
import model37 from "./models/FrozenR6-U5.glb";
import model38 from "./models/RemoteBase.glb";
import model39 from "./models/RemoteBase-cutaway.glb";
import model40 from "./models/RemoteLid.glb";
import model41 from "./models/RemoteLid-cutaway.glb";
import model42 from "./models/StatusRingLightGuide.glb";
import model43 from "./models/ChargeWindowLightGuide.glb";
import model44 from "./models/ShutterPlunger.glb";
import model45 from "./models/PairPlunger.glb";
import model46 from "./models/ShutterSoftSkin.glb";
import model47 from "./models/PowerSlider.glb";
import model48 from "./models/BatteryCarrier.glb";
import model49 from "./models/BatteryDTP401525MaximumEnvelope.glb";
import model50 from "./models/MagneticGripDock.glb";
import model51 from "./models/BatteryThermalPadCompressedEnvelope.glb";
import model52 from "./models/BatteryHarnessPositiveReservation.glb";
import model53 from "./models/BatteryHarnessNegativeReservation.glb";
import model54 from "./models/PhoneReceiverPlateEnvelope.glb";
import model55 from "./models/LidScrewM2x14Left.glb";
import model56 from "./models/M2InsertEnvelopeLeft.glb";
import model57 from "./models/LidScrewM2x14Right.glb";
import model58 from "./models/M2InsertEnvelopeRight.glb";
import model59 from "./models/RemoteMagnetLeft.glb";
import model60 from "./models/DockMagnetLeft.glb";
import model61 from "./models/RemoteMagnetInsulatingCapLeft.glb";
import model62 from "./models/DockMagnetInsulatingCapLeft.glb";
import model63 from "./models/RemoteMagnetRight.glb";
import model64 from "./models/DockMagnetRight.glb";
import model65 from "./models/RemoteMagnetInsulatingCapRight.glb";
import model66 from "./models/DockMagnetInsulatingCapRight.glb";
import model67 from "./models/PhoneMagnetLeft28.glb";
import model68 from "./models/PhoneMagnetInsulatingCapLeft28.glb";
import model69 from "./models/PhoneMagnetLeft56.glb";
import model70 from "./models/PhoneMagnetInsulatingCapLeft56.glb";
import model71 from "./models/PhoneMagnetRight28.glb";
import model72 from "./models/PhoneMagnetInsulatingCapRight28.glb";
import model73 from "./models/PhoneMagnetRight56.glb";
import model74 from "./models/PhoneMagnetInsulatingCapRight56.glb";
export const modelUrls: Record<string, string> = {
	"FrozenR6-Box0.glb": model0,
	"FrozenR6-C1.glb": model1,
	"FrozenR6-C2.glb": model2,
	"FrozenR6-C3.glb": model3,
	"FrozenR6-C4.glb": model4,
	"FrozenR6-C5.glb": model5,
	"FrozenR6-C6.glb": model6,
	"FrozenR6-C7.glb": model7,
	"FrozenR6-C8.glb": model8,
	"FrozenR6-C9.glb": model9,
	"FrozenR6-J1.glb": model10,
	"FrozenR6-J2.glb": model11,
	"FrozenR6-J3.glb": model12,
	"FrozenR6-LED1.glb": model13,
	"FrozenR6-LED2.glb": model14,
	"FrozenR6-Q1.glb": model15,
	"FrozenR6-Q2.glb": model16,
	"FrozenR6-R1.glb": model17,
	"FrozenR6-R10.glb": model18,
	"FrozenR6-R11.glb": model19,
	"FrozenR6-R12.glb": model20,
	"FrozenR6-R13.glb": model21,
	"FrozenR6-R2.glb": model22,
	"FrozenR6-R3.glb": model23,
	"FrozenR6-R4.glb": model24,
	"FrozenR6-R5.glb": model25,
	"FrozenR6-R6.glb": model26,
	"FrozenR6-R7.glb": model27,
	"FrozenR6-R8.glb": model28,
	"FrozenR6-R9.glb": model29,
	"FrozenR6-SW1.glb": model30,
	"FrozenR6-SW2.glb": model31,
	"FrozenR6-SW3.glb": model32,
	"FrozenR6-U1.glb": model33,
	"FrozenR6-U2.glb": model34,
	"FrozenR6-U3.glb": model35,
	"FrozenR6-U4.glb": model36,
	"FrozenR6-U5.glb": model37,
	"RemoteBase.glb": model38,
	"RemoteBase-cutaway.glb": model39,
	"RemoteLid.glb": model40,
	"RemoteLid-cutaway.glb": model41,
	"StatusRingLightGuide.glb": model42,
	"ChargeWindowLightGuide.glb": model43,
	"ShutterPlunger.glb": model44,
	"PairPlunger.glb": model45,
	"ShutterSoftSkin.glb": model46,
	"PowerSlider.glb": model47,
	"BatteryCarrier.glb": model48,
	"BatteryDTP401525MaximumEnvelope.glb": model49,
	"MagneticGripDock.glb": model50,
	"BatteryThermalPadCompressedEnvelope.glb": model51,
	"BatteryHarnessPositiveReservation.glb": model52,
	"BatteryHarnessNegativeReservation.glb": model53,
	"PhoneReceiverPlateEnvelope.glb": model54,
	"LidScrewM2x14Left.glb": model55,
	"M2InsertEnvelopeLeft.glb": model56,
	"LidScrewM2x14Right.glb": model57,
	"M2InsertEnvelopeRight.glb": model58,
	"RemoteMagnetLeft.glb": model59,
	"DockMagnetLeft.glb": model60,
	"RemoteMagnetInsulatingCapLeft.glb": model61,
	"DockMagnetInsulatingCapLeft.glb": model62,
	"RemoteMagnetRight.glb": model63,
	"DockMagnetRight.glb": model64,
	"RemoteMagnetInsulatingCapRight.glb": model65,
	"DockMagnetInsulatingCapRight.glb": model66,
	"PhoneMagnetLeft28.glb": model67,
	"PhoneMagnetInsulatingCapLeft28.glb": model68,
	"PhoneMagnetLeft56.glb": model69,
	"PhoneMagnetInsulatingCapLeft56.glb": model70,
	"PhoneMagnetRight28.glb": model71,
	"PhoneMagnetInsulatingCapRight28.glb": model72,
	"PhoneMagnetRight56.glb": model73,
	"PhoneMagnetInsulatingCapRight56.glb": model74,
};
