// Native board markings; immutable supplier footprints are preserved.
export function FunctionalMarkings() {
	return (
		<>
			<silkscreentext
				text="SHUTTER"
				pcbX={-9.25}
				pcbY={-12}
				layer="top"
				fontSize={2}
				pcbRotation={90}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="1"
				pcbX={15.7}
				pcbY={19.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="POWER"
				pcbX={11.4}
				pcbY={4.5}
				layer="top"
				fontSize={2}
				pcbRotation={90}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="BAT"
				pcbX={-13.5}
				pcbY={20.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="PAIR"
				pcbX={12.0}
				pcbY={-8.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="SWD 1:3V"
				pcbX={11.0}
				pcbY={26.5}
				layer="bottom"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="2:IO 3:GND"
				pcbX={10.0}
				pcbY={1.5}
				layer="bottom"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="4:CLK 5:RST"
				pcbX={5.0}
				pcbY={-2.5}
				layer="bottom"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="6:GND"
				pcbX={12.0}
				pcbY={17.0}
				layer="bottom"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="LED1"
				pcbX={12.5}
				pcbY={26.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="LED2"
				pcbX={5.5}
				pcbY={0.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="SW2"
				pcbX={-13.5}
				pcbY={-9.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="SW3"
				pcbX={13.5}
				pcbY={-10.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="SW1"
				pcbX={15.0}
				pcbY={10.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R10"
				pcbX={-11.0}
				pcbY={4.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R11"
				pcbX={3.0}
				pcbY={-2.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R12"
				pcbX={12.0}
				pcbY={12.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R13"
				pcbX={12.0}
				pcbY={20.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="J1"
				pcbX={-6.5}
				pcbY={23.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R1"
				pcbX={-7.0}
				pcbY={19.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R2"
				pcbX={3.0}
				pcbY={14.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="U2"
				pcbX={-6.5}
				pcbY={14.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R3"
				pcbX={7.0}
				pcbY={14.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C1"
				pcbX={16.0}
				pcbY={21.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C2"
				pcbX={8.0}
				pcbY={2.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R4"
				pcbX={16.0}
				pcbY={23.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="J2"
				pcbX={-15.0}
				pcbY={6.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R8"
				pcbX={-7.0}
				pcbY={21.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R9"
				pcbX={-7.0}
				pcbY={25.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C8"
				pcbX={16.0}
				pcbY={12.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C9"
				pcbX={-9.5}
				pcbY={2.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="U1"
				pcbX={9.5}
				pcbY={-15.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C5"
				pcbX={-1.0}
				pcbY={-2.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R7"
				pcbX={4.0}
				pcbY={-4.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="J3"
				pcbX={11.5}
				pcbY={-1.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R5"
				pcbX={-5.5}
				pcbY={-6.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="Q1"
				pcbX={-13.0}
				pcbY={-1.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="R6"
				pcbX={-15.0}
				pcbY={4.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="U3"
				pcbX={-11.5}
				pcbY={-3.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C3"
				pcbX={-15.0}
				pcbY={-3.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C4"
				pcbX={-12.0}
				pcbY={-11.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="U4"
				pcbX={-16.0}
				pcbY={1.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C6"
				pcbX={-15.5}
				pcbY={-11.5}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="U5"
				pcbX={9.5}
				pcbY={-10.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="C7"
				pcbX={-10.5}
				pcbY={22.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreentext
				text="Q2"
				pcbX={9.5}
				pcbY={-12.0}
				layer="top"
				fontSize={2}
				pcbRotation={0}
				anchorAlignment="center"
			/>
			<silkscreenpath
				layer="top"
				strokeWidth={0.18}
				route={[
					{ x: -15.1, y: 17.9 },
					{ x: -13.9, y: 17.9 },
				]}
			/>
			<silkscreenpath
				layer="top"
				strokeWidth={0.18}
				route={[
					{ x: -14.5, y: 17.3 },
					{ x: -14.5, y: 18.5 },
				]}
			/>
			<silkscreenpath
				layer="top"
				strokeWidth={0.18}
				route={[
					{ x: -13.1, y: 17.9 },
					{ x: -11.9, y: 17.9 },
				]}
			/>
		</>
	);
}
