// Native functional legends; supplier artwork remains unchanged.
export function FunctionalMarkings() {
	return (
		<>
			<silkscreentext
				text="SHUTTER"
				pcbX={15}
				pcbY={-11.5}
				layer="top"
				fontSize={1.8}
			/>
			<silkscreentext
				text="PAIR"
				pcbX={17}
				pcbY={-5}
				layer="top"
				fontSize={1.8}
			/>
			<silkscreentext
				text="BOOT"
				pcbX={-18}
				pcbY={-11.5}
				layer="top"
				fontSize={1.8}
			/>
			<silkscreentext
				text="RESET"
				pcbX={14.5}
				pcbY={8.9}
				layer="top"
				fontSize={1.8}
			/>
			<silkscreentext
				text="POWER"
				pcbX={18}
				pcbY={0}
				layer="top"
				fontSize={1.8}
			/>
			<silkscreentext
				text="BAT 1:- 2:+"
				pcbX={-14}
				pcbY={17}
				layer="top"
				fontSize={1.8}
			/>
			<silkscreentext
				text="1"
				pcbX={16}
				pcbY={19.5}
				layer="top"
				fontSize={1.8}
			/>
		</>
	);
}
