import type { FanoutTracePath } from "@tscircuit/core";
// Native board copper; supplier footprint and pin mapping are unchanged.
export const sensorEscapePaths: FanoutTracePath[] = [
	{
		connection: "U5.pin1",
		route: [
			{
				route_type: "wire",
				x: 0.7499858,
				y: 5.500001,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 1.3,
				y: 5.500001,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 2,
				y: 4.8,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: 2,
				y: 4.8,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.45,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U5.pin2",
		route: [
			{
				route_type: "wire",
				x: 0.7499858,
				y: 5.999873,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 1.3,
				y: 5.999873,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 2.3,
				y: 6,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: 2.3,
				y: 6,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.45,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U5.pin3",
		route: [
			{
				route_type: "wire",
				x: 0.7499858,
				y: 6.499999,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 1.3,
				y: 6.499999,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: 2,
				y: 7.2,
				width: 0.15,
				layer: "top",
			},
			// Keep the sensor return on top to its decoupling-capacitor return.
			{ route_type: "wire", x: 2, y: 7.2, width: 0.15, layer: "top" },
			{ route_type: "wire", x: 3.2, y: 8.4, width: 0.15, layer: "top" },
			{ route_type: "wire", x: 3.2, y: 8.5, width: 0.15, layer: "top" },
		],
	},
	{
		connection: "U5.pin4",
		route: [
			{
				route_type: "wire",
				x: -0.7499858,
				y: 6.499999,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -1.3,
				y: 6.499999,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -2,
				y: 7.2,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -2,
				y: 7.2,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.45,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U5.pin5",
		route: [
			{
				route_type: "wire",
				x: -0.7499858,
				y: 5.999873,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -1.3,
				y: 5.999873,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -2.3,
				y: 6,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -2.3,
				y: 6,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.45,
				via_hole_diameter: 0.3,
			},
		],
	},
	{
		connection: "U5.pin6",
		route: [
			{
				route_type: "wire",
				x: -0.7499858,
				y: 5.500001,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -1.3,
				y: 5.500001,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "wire",
				x: -2,
				y: 4.8,
				width: 0.15,
				layer: "top",
			},
			{
				route_type: "via",
				x: -2,
				y: 4.8,
				from_layer: "top",
				to_layer: "bottom",
				via_diameter: 0.45,
				via_hole_diameter: 0.3,
			},
		],
	},
];
